# Generated by Django 6.1.1 on 2026-09-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0003_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightManifest',
            fields=[
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flights_app.flight')),
                ('notes', models.TextField()),
            ],
        ),
    ]
