# Generated by Django 6.1.1 on 2026-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0004_flightmanifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='passenger_images/'),
        ),
    ]
